a= int(input ("How many money do you have? "))
b= int(input ("What is the price for an apple? "))
apple= ( a / b )
change= ( a - (apple * b ))
print (f"You can buy {apple} apples and your change is {change} pesos")
